spring:
  application:
    name: "spring-security"
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#   security:
#     jwt:
#       secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
#       expiration-time: 86400000

logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO



server:
  error:
    include-stacktrace: never

# 24h in millisecond
