spring:
  application:
    name: "spring-security"
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#   security:


logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO



server:
  error:
    include-stacktrace: never

# 24h in millisecond
